CREATE DATABASE IF NOT EXISTS restaurant_db;
USE restaurant_db;



CREATE TABLE IF NOT EXISTS menu_item (
    id INT PRIMARY KEY AUTO_INCREMENT,
    price DECIMAL(10, 2),
    type VARCHAR(150) NOT NULL,
    name VARCHAR(150) NOT NULL,
    status ENUM('AVAILABLE', 'DISABLED', 'OUT_OF_STOCK') NOT NULL DEFAULT 'AVAILABLE'
);

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    password VARCHAR(250) NOT NULL,
    role ENUM('CUSTOMER', 'CHEF', 'MANAGER') NOT NULL DEFAULT 'CUSTOMER',
    status ENUM('ACTIVE', 'DISABLE') NOT NULL DEFAULT 'ACTIVE',
    UNIQUE KEY uk_users_name (name)
);

select  * from users;
INSERT IGNORE INTO users(name, password, role)
VALUES ('admin', '$2a$10$3f2.e61.HJDDjKZyYWGCvevWj3.QnmAIPMyXdpK3iHGouReUpG5Ka', 'MANAGER');


select * from users;
CREATE TABLE IF NOT EXISTS tableRs (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL,
    capacity INT NOT NULL,
    status ENUM('AVAILABLE', 'OCCUPIED') NOT NULL DEFAULT 'AVAILABLE'
);

CREATE TABLE IF NOT EXISTS orders (
    id INT PRIMARY KEY AUTO_INCREMENT,
    userId INT NOT NULL,
    tableId INT NOT NULL,
    status ENUM('CheckIn', 'CheckOuted') NOT NULL DEFAULT 'CheckIn',
    approved BOOLEAN DEFAULT FALSE,
    total DECIMAL(10,2) DEFAULT 0,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES users(id),
    FOREIGN KEY (tableId) REFERENCES tableRs(id)
);




CREATE TABLE IF NOT EXISTS orderItem (
    id INT PRIMARY KEY AUTO_INCREMENT,
    orderId INT NOT NULL,
    menuItemId INT NOT NULL,
    quantity INT NOT NULL,
    status ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
    FOREIGN KEY (orderId) REFERENCES orders(id),
    FOREIGN KEY (menuItemId) REFERENCES menu_item(id)
);

select * from orderItem;

CREATE TABLE IF NOT EXISTS review (
    id INT PRIMARY KEY AUTO_INCREMENT,
    userId INT NOT NULL,
    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT DEFAULT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES users(id)
);


ALTER TABLE orderItem
    MODIFY status ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'CANCELLED', 'DELETED')
        NOT NULL DEFAULT 'PENDING';

ALTER TABLE tableRs
    MODIFY status ENUM('AVAILABLE', 'OCCUPIED', 'DELETED')
        NOT NULL DEFAULT 'AVAILABLE';

ALTER TABLE menu_item
    MODIFY status ENUM('AVAILABLE', 'DISABLED', 'OUT_OF_STOCK', 'DELETED')
        NOT NULL DEFAULT 'AVAILABLE';

select * from tableRs;